version: '3.7'

services:
  nginx:
    image: ${NGINX_IMG}
    ports:
      - ${PORT}:80
    volumes:
      - ${PROJECT_DIR}/taskmanager/static:/static:Z,rw
    depends_on:
      - web
      - dtb

  web:
    image: ${PY_IMG}
    restart: on-failure
    working_dir: /var/www
    env_file:
      - ${PROJECT_DIR}/.env
    volumes:
      - ${PROJECT_DIR}/taskmanager:/var/www:Z,rw
    depends_on:
      - dtb

  dtb:
    image: ${DTB_IMG}
    restart: on-failure
    env_file:
      - ${PROJECT_DIR}/.env
    ports:
      - ${DTB_PORT}:3306
    volumes:
      - dtb:/var/lib/mysql:rw

  phpmyadmin:
    image: ${PMA_IMG}
    restart: on-failure
    ports:
      - ${PMA_PORT}:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  dtb: